package com.laowen.auth.dao;

import com.laowen.auth.domain.RefUserRole;

public interface RefUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    int insert(RefUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    int insertSelective(RefUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    RefUserRole selectByPrimaryKey(String refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RefUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RefUserRole record);
}