package com.laowen.auth.dao;

import com.laowen.auth.domain.SysResources;

public interface SysResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String resourcesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    int insert(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    int insertSelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    SysResources selectByPrimaryKey(String resourcesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysResources record);
}